# Generated by Django 3.1.5 on 2021-01-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20210119_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttocomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commenttocomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_comment', to='app.commenttoarticle'),
        ),
        migrations.AlterField(
            model_name='disliketocomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disliketocomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.commenttoarticle'),
        ),
    ]
