# Generated by Django 3.1.5 on 2021-01-23 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210123_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttoarticle',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
